### ISSUE TITLE
The new tests are failing on me

### ISSUE THREAD

**Issue by AndrewSav** [ngn/apl#99]
After latest commit the build itself works, but the tests at the end fail:

```
/opt/apl/test/rundoctests.js:2
const apl=require('../lib/apl'),{runDocTest}=require('./rundoctest'),si=process.stdin,so=process.stdout
                                ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:907:11)
    at WriteWrap.afterWrite (net.js:787:14)
```

Any idea why my node does not understand the curly bracket?

**Comment by AndrewSav** [comment]
Apparently I need to upgrade my node
